---
networks:
  nginx_net:
    name: nginx_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.118.100.0/24"
          gateway: "10.118.100.1"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /docker/traefik/${SERVER}/letsencrypt:/etc/traefik/acme
      - /docker/traefik/${SERVER}/logs:/opt/logs
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN}
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
    command:
      # access log
      - --accesslog=true
      - --accesslog.filepath=/opt/logs/access.log
      - --log.filePath=/opt/logs/traefik.log
      # Enable dashboard
      - --api.dashboard=true
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Skip internal cert check
      - --serversTransport.insecureSkipVerify=true
      # Entrypoints
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      # Certificates
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${LETS_ENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
      # needed so internal DNS doesn't dick with things
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      # CF Middleware
      - --experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp
      - --experimental.plugins.cloudflarewarp.version=v1.3.3
    labels:
      # Dashboard config
      - traefik.enable=true
      - traefik.http.routers.traefik-dash.rule=Host(`${SERVER}.${DOMAIN}`)
      - traefik.http.routers.traefik-dash.entrypoints=websecure
      - traefik.http.routers.traefik-dash.service=api@internal
      - traefik.http.routers.traefik-dash.tls.certResolver=letsencrypt
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
